version: "2"

networks:
  ca-network:

services:
  # ca-root:
  #   container_name: ca-root
  #   image: hyperledger/fabric-ca:$IMAGE_TAG
  #   environment:
  #     - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
  #     - ROOT_HOST=ca-root
  #     - ROOT_PORT=7054
  #     - ROOT_USERNAME=admin
  #     - ROOT_PASSWORD=adminpw
  #   volumes:
  #   #   - ./state/ca-root:/etc/hyperledger/fabric-ca-server
  #     - ./scripts:/scripts
  #   command: sh /scripts/start-root.sh
  #   ports:
  #     - 7054:7054
  #   networks:
  #     - byfn
  ca:
    container_name: ca
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-server
      # - ROOT_HOST=ca-root
      # - ROOT_PORT=7054
      # - ROOT_USERNAME=admin
      # - ROOT_PASSWORD=adminpw
      - HOST=ca
      - PORT=7054
      - USERNAME=admin
      - PASSWORD=adminpw
    volumes:
      - /tmp/hyperledger/tls/ca:/tmp/hyperledger/fabric-ca
    #   - ./state/ca-intermediate:/etc/hyperledger/fabric-ca-server
    #   - ./state/ca-root:/etc/hyperledger/fabric-ca-server-root
    #   - ./scripts:/scripts
    # command: sh /scripts/start-intermediate.sh
    command: sh -c 'fabric-ca-server start -d -b admin:adminpw --port 7054'
    # command: fabric-ca-server start -b admin:adminpw
    ports:
      - 7054:7054
    networks:
      - ca-network
    # depends_on:
    #   - ca-root
  ca-client:
    container_name: ca-client
    image: hyperledger/fabric-ca-tools:$IMAGE_TAG
    working_dir: /etc/hyperledger/fabric-ca-client
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca-client
      # - ROOT_HOST=ca-root
      # - ROOT_PORT=7054
      # - ROOT_USERNAME=admin
      # - ROOT_PASSWORD=adminpw
      - HOST=ca
      - PORT=7054
      - USERNAME=admin
      - PASSWORD=adminpw
    volumes:
    #   - ./state/ca-intermediate:/etc/hyperledger/fabric-ca-server-intermediate
    #   - ./state/ca-root:/etc/hyperledger/fabric-ca-server-root
    #   - ./state/ca-client:/etc/hyperledger
      - ./scripts:/etc/hyperledger/fabric-ca-client/scripts
    command: sleep infinity
    networks:
      - ca-network
    depends_on:
      # - ca-root
      - ca